//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MJ.Common.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public System.Guid commentId { get; set; }
        public string commentText { get; set; }
        public System.Guid commenterId { get; set; }
        public System.DateTime commentDateTime { get; set; }
        public bool commentDeleted { get; set; }
    
        public virtual SystemUser SystemUser { get; set; }
    }
}
