//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MJ.Common.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemUser
    {
        public SystemUser()
        {
            this.Comments = new HashSet<Comment>();
            this.Posts = new HashSet<Post>();
        }
    
        public System.Guid userId { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string pwdSalt { get; set; }
        public System.Guid userTypeId { get; set; }
        public bool isActive { get; set; }
        public bool needsPasswordReset { get; set; }
        public System.DateTime datetimeCreated { get; set; }
        public Nullable<System.DateTime> datetimeUpdated { get; set; }
        public Nullable<System.DateTime> datetimeDeleted { get; set; }
    
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<Post> Posts { get; set; }
        public virtual UserType UserType { get; set; }
    }
}
