//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MJ.Common.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserType
    {
        public UserType()
        {
            this.SystemUsers = new HashSet<SystemUser>();
        }
    
        public System.Guid userTypeId { get; set; }
        public string userTyped { get; set; }
    
        public virtual ICollection<SystemUser> SystemUsers { get; set; }
    }
}
